### ISSUE TITLE
No way to paste schematics

### ISSUE THREAD

**Issue by HJBLink** [Amulet-Team/Amulet-Map-Editor#23]
Is there a way to paste schematics? I read the instructions on the program but I can't seem to figure out how to paste a schematic.

**Comment by Podshot** [comment]
Amulet currently can only copy structures from one opened world to another, we have plans to add importing of schematics at some point, but that will not be for a decent amount of time since the schematic format is out of date and not suitable for transferring builds across different Minecraft editions. 

However, we are currently adding support for a new format that we hope will eventually replace the schematic format and allow better compatibility of moving builds across the various editions, this will be implemented before we go back and revisit schematics.
