### ISSUE TITLE
Option to cancel or bypass creating a undo point

### ISSUE THREAD

**Issue by lilggamegenius** [Amulet-Team/Amulet-Map-Editor#279]
**Has your feature request already been suggested? Please check if your suggested feature has already been suggested.**
I didn't seen any feature requests related to the undo function

**Is your feature request related to a problem? Please describe.**
I am trying to do some chunk pruning on a very large world (2GB when zipped with medium compression)
and when I start the pruning, the estimated time instantly shoots to about 6 hours before I force closed the program since there was no way to cancel the operation

**Describe the solution you'd like**
I think either an option to cancel making the undo point or having the option to skip (at least for ones with long wait times) would be perfect

**Describe alternatives you've considered**
The only alternative I can think of is just letting it run through but I think I will clone and make a quick hack to bypass this

**Additional context**
This is what I would like to avoid doing
![image](https://user-images.githubusercontent.com/6175821/116843291-209c4d80-aba5-11eb-82f3-60f13c3e8204.png)

**Comment by gentlegiantJGC** [comment]
This is something I have thought about adding and plan to at some point

**Comment by Moilleadoir** [comment]
This is incredibly annoying. I’m already working on a copy so I really don’t need this and it’s taken much more time to create the undo (~35 mins) than it took to edit.

**Comment by gentlegiantJGC** [comment]
This is mostly due to how our architecture is set up.
The main aim of it is to push all of the loaded chunks to a cache on disk so that your computer's RAM is not filled up with all the loaded chunks. As a side effect with little computational overhead we get a history system.
The issue is that the delete chunk and delete unselected chunk operations run on chunks that have not been loaded so they too need to be loaded.

I added an option in the last build when you click on either of those operations to not load the original chunks which should make the process a lot quicker.

**Comment by Moilleadoir** [comment]
I saw the change and made good use of it! Thanks for the quick response. Meant to thank you but I just got busy with other stuff.
