### ISSUE TITLE
Removing a Nether Portal Creates a Ghost Portal (Minecraft BE)

### ISSUE THREAD

**Issue by ForestOfGold** [Amulet-Team/Amulet-Map-Editor#290]
**Description**
If two portals are linked and Amulet moves or removes one of them, they lead to the same spot as before the edit. *Tested in Bedrock only*

**To Reproduce**
1. Create a portal in the overworld and go to the nether with it.
2. Use Amulet to delete or move the physical portal blocks in the nether.
3. Go through the overworld side of the portal again and end up in the nether with no portal, but still in the same place.

**Expected behavior**
When going through the portal, the game should behave normally as if there was never any portal (ie. a new one is created or linked up).

**Video**
https://user-images.githubusercontent.com/77603428/117615992-6023e600-b11f-11eb-9cfd-5bc78913844d.mp4

**Desktop**
 - Windows 10
 - Minecraft 1.16.221

**Comment by gentlegiantJGC** [comment]
This is beyond the scope of Amulet. Bedrock saves the exit location in metadata in the db. To fix this we would have to check for each operation if a portal is modified and then go digging in the db to find that data.

**Comment by jackytsheng** [comment]
@ForestOfGold I had the same issue. Problem is that Portal data persist after the chunk is deleted. 
In my case even both over world and nether portal are deleted it will still have the ghost portal effect.

Then I found this [Universal Minecraft Editor](https://www.universalminecrafteditor.com/5glXX1pcDtTpIhlScl37.html)

I open my world using window 10 laptop. And Select **View files**, under **db**, there should exist **portal** 
![image](https://user-images.githubusercontent.com/48374842/127729379-b9ef081d-17fe-4810-be11-4a086d9e7aa2.png)

you may want to locate the position where the ghost portal effect occurs and delete it. But I deleted all of them because I don't have any important build in the nether. That should fix the problem.

Hope that helps !

**Comment by ForestOfGold** [comment]
Oh yeah, UMC can totally be used for this. Thanks!

**Comment by demifiend9** [comment]
FoxyNoTail's MCBE Prune tool app deletes chunks and automatically clears the portal data of the corresponding chunks. If that program is smart enough to do that, I would have guessed Amulet being a much more advanced program would have done the same, but unfortunately this issue is marked as wontfix.

I think you should atleast mention this in Amulet FAQ that deleting chunks in bedrock worlds can lead to ghost portals.
