### ISSUE TITLE
Add sub-chunk logic

### ISSUE THREAD

**Issue by naor2013** [Amulet-Team/Amulet-Map-Editor#31]
Add sub-chunks to chunks where you can save things into the sub-chunks and it will be considered as part of the chunk. Can be used for blocks but is mostly needed for entities.

**Comment by Podshot** [comment]
Instead of adding the logic to `SubChunk`, there is now a `get_entities_in_box()` method that returns a generator of all entities inside the given selection and keeps track of entities that are in a chunk, but not in the selection box. There is also an `add_entities()` method that handles placing the entity in the correct chunk. Closing this issue since these changes are included in #44
