### ISSUE TITLE
VirusTotal reports 5 negative hits

### ISSUE THREAD

**Issue by UsualNote1** [Amulet-Team/Amulet-Map-Editor#538]
Thanks for the new version! 

VirusTotal is reporting five negative hits on the Amulet.exe app. The hits are mostly from minor services, but also McAfee flags it, which some people will take seriously. 

https://www.virustotal.com/gui/file/c93b5e3c0ae4023d25cfbc319d7cb0b3b4cac7a68cd29c0b054c60b59d0f1462

Appreciate your work on this app.

**Comment by gentlegiantJGC** [comment]
Looks like some of those are now not listed.
I don't know what we can do to improve this since I don't know how they detect if it is a problem or not.
What even counts as a virus?

I think they usually have a false positive reporting page.
The only true solution to this would be getting a signing certificate but that costs a bit of money.

**Comment by gentlegiantJGC** [comment]
I am going to close this and continue tracking the issue in #141
