### ISSUE TITLE
Unable to use "Set Biome" feature for ungenerated/deleted chunks in the new 1.18 version

### ISSUE THREAD

**Issue by MineKraftplayer** [Amulet-Team/Amulet-Map-Editor#554]
When trying to use the "Set Biome" feature for not yet generated or deleted chunks, it doesn't work, only the already existing chunks get a change in biome.

This worked to my knowledge fine when I tried it on a 1.17 world with the version of amulet that had 1.17 as latest.

What I did was:
- going to "Chunk"
- select an area of not yet generated Chunks
- went to "operations"," set biome"
- selected a biome
- ran the operation
- saved

The save was successful, as all other changes were present.

Thanks for the help!

**Comment by gentlegiantJGC** [comment]
The set biome operation has only ever worked on existing chunks. I don't know if our code creates them as void if they don't exist.

**Comment by lypoluz** [comment]
It works with already generated chunks though, as intended.
Latest version of both Minecraft and Amulet.

**Comment by gentlegiantJGC** [comment]
Just looked through our code and we do in fact only set biomes for chunks that exist.
I think this is the correct behaviour since only chunks that exist can have biomes.
The alternative is to create the chunk first but we only have the ability to create a void chunk.

I think we should implement a chunk operation to create void chunks as suggested in #393 so that users can create their own chunks.

I think creation of void chunks is beyond the scope of the set biome operation.
