### ISSUE TITLE
typo in the README.md

### ISSUE THREAD

**Issue by Tommie1236** [Amulet-Team/Amulet-Map-Editor#607]
there is a little typo in the readme.md file, in the section where it says python -> python3 it says "If you have python 2 installed python may point to the wrong version in which case you will have to swap out python for python3" so python 3 instead of python2

**Comment by jimbt** [comment]
Python version 3 is required.  The readme is indicating that you may need to execute python version 3 using the 'python3' command instead of just 'python' since 'python' may execute python version 2.

**Comment by Tommie1236** [comment]
I know that, maybe I wasn't clear enough about it

**Comment by jimbt** [comment]
Ok, so what is the typo?  Or did you think it could be made more clear?

**Comment by Tommie1236** [comment]
i read this on the website just a few minutes before here, it just said it differently on the website and that one made more sense to me back then, so not really a typo i think then
this is what the website says:
"On some operating systems Python 3 uses the command python3 rather than just python so you will need to swap that out if that is the case."
but python2 is also fine, maybe make it "python, python2"

**Comment by gentlegiantJGC** [comment]
This code doesn't run with python 2.
The issue is that on some operating systems (eg Windows) the installer sets up the system variable `python` so on Windows `python` will get python 3 but on Linux they have `python` for python 2 and `python3` for python 3.

If you still think this is an issue please can you explain better. I am struggling to understand the issue.

**Comment by Tommie1236** [comment]
oke, then leave it as it is. i didn't know that just thougt it would be a typo on one of them since they don't say the same.
