### ISSUE TITLE
[Bug Report] Amulet does... whatever this is meant to be when converting Bedrock to Java

### ISSUE THREAD

**Issue by Hedwig7s** [Amulet-Team/Amulet-Map-Editor#654]
## Bug Report
Amulet made chunks of 1 block for some reason
### Current Behaviour:
![2022-04-28_10 24 33](https://user-images.githubusercontent.com/51961150/165711514-c7983171-747e-46f9-b5ce-4b8c5ce71a7d.png)

### Expected behavior:
For the world to convert

### Steps To Reproduce:
1 Convert a World from Bedrock to Java

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock > Java
- Minecraft Version: Bedrock 1.18.30 Java 1.18.2
- Amulet Version: 0.9.2

### Screenshots
![2022-04-28_10 20 28](https://user-images.githubusercontent.com/51961150/165711777-2226ed26-9177-4858-838d-bb9cdac9eb55.png)
![2022-04-28_10 24 33](https://user-images.githubusercontent.com/51961150/165711812-22fe5257-9815-45e0-8750-8cd37e172758.png)

### Worlds
Original World: https://filebin.net/fqor5c5rj56hd3z8
Converted Worlds: https://filebin.net/y4tba9m5eiup0c4l

**Comment by gentlegiantJGC** [comment]
It looks like this issue comes from the source Bedrock world.
It is due to the sub-chunks being stored in different formats which probably does not happen very often which is why I have not seen this issue before.
When unpacking the palette the same block is added multiple times but in different formats which later stack making the palette smaller.
