### ISSUE TITLE
Rotation of blocks

### ISSUE THREAD

**Issue by Reender** [Amulet-Team/Amulet-Map-Editor#74]
When rotating and pasting a copied selection, most importantly on the x and z-axis, it doesn't rotate the stairs accordingly.
At this point this is really the only feature missing, for me to use amulet for projects.

Thanks for reading :) Hope this gets added in the future.

![image](https://user-images.githubusercontent.com/11940194/111910993-987e4080-8a5b-11eb-98ff-2743d4cfcda5.png)

**Comment by frankicool2010** [comment]
any update on this bug correction ?? i just report it and my ticket and it was close.

seems to be a old bug from 2020 and it wasn't patched ?

thank to keep us inform about this

**Comment by jhthorp** [comment]
Hello,
I am having the same issue except more critically with Redstone components (Repeaters, Comparators, Observers, Pistons, etc.).  This is all part of a very large build that I am using as a model.

Can you provide a rough ETA on this so that I can decide about manually rotating everything or waiting for a fix?

Thanks for such a great tool! 

Of note, I am a Software Engineer and would gladly take a look at the relevant code if it would help.

**Comment by zeekblitz** [comment]
Is there a way to upvote this for priority? The editor is basically useless for me until this is fixed.

**Comment by MorganShady** [comment]
Please, fix this problem.

**Comment by SinQ882** [comment]
Is there any indication that this is being worked on? As I read it this will take a lot of work, but I'm trying to decide if I should wait or find something else.

**Comment by gentlegiantJGC** [comment]
This is now implemented in the latest beta. It will get a full release if there are no bugs found.
