### ISSUE TITLE
Desktop Shortcut Bug

### ISSUE THREAD

**Issue by ghost** [Amulet-Team/Amulet-Map-Editor#766]
### Current Behaviour:

When I drag a desktop icon and it touches the Amulet desktop shortcut I made, the desktop freezes and then crashes.
### Expected behavior:

I was expecting the desktop icon to be moved from the top left corner to where I wanted it to be placed without issue. (Note: the origin of the desktop icon being moved doesn't matter. If it touches the Amulet shortcut, the desktop crashes.)
### Steps To Reproduce:
1. Hold Click on Desktop Icon
2. Drag Desktop Icon across Amulet Shortcut Icon on Desktop
3. Watch the desktop freeze, try to recover (which it may do), then crash making the desktop inaccessible and the file explorer to open.

### Environment:

- OS: Windows 10
- Amulet Version: 0.9.6

### Additional context

Last month, I tried reorganizing my desktop by dragging icons about, only to find it crashing. So, I used trial and error and found that it was my Amulet Shortcut. I deleted Amulet, reinstalled it, and it was fine. Though today, it is back to what it was doing before. I also found out today that I can drag the desktop recycling bin over the Amulet Shortcut, but not any other icon on my desktop. (Examples of the other icons are folders, other shortcuts, the Minecraft Java and Bedrock launchers, the Apex Legends .exe shortcut I made, and other Steam game shortcuts.)
If the easiest solution is to not have a shortcut icon, then I'll just remove the shortcut.

**Comment by ghost** [comment]
I would like to add that I have my desktop connected to Onedrive, so the shortcut is connected to the cloud, or however that works. Also, when I first had this problem, deleting or moving the Amulet Shortcut would cause the desktop to crash, but currently it isn't doing that. So, that's nice.

**Comment by gentlegiantJGC** [comment]
I am fairly confident that this isn't an issue with Amulet because Amulet isn't actually running.

This sounds more like an OS issue because no program should be able to crash the desktop (windows explorer)

It might be an issue with the OS resolving the real path (although I don't know why it would be when you are just hovering)

There is a feature of windows where you can drag and drop a file onto an exe or shortcut and it will run the program with the dragged file as an argument to the program. That should only happen when you release the left click while hovering which you aren't.

Do you by chance have Amulet on a different HDD that needs to spin up to access the data?

**Comment by ghost** [comment]
I don't have Amulet on a different drive. I have it on an SSD which I have everything on.

**Comment by gentlegiantJGC** [comment]
I honestly don't think this is an issue with Amulet since it is happening when you moved files around which is entirely OS based.

I am going to close this because it isn't an issue on our end. Perhaps try moving it out of your onedrive.
