### ISSUE TITLE
[Bug Report] Blocks Cannot Be Replaced with Border Blocks

### ISSUE THREAD

**Issue by qmagnet** [Amulet-Team/Amulet-Map-Editor#815]
### Current Behaviour:
Blocks cannot be replaced with border_block for Bedrock

### Expected behavior:
Blocks should be able to be replaced with border blocks

### Steps To Reproduce:
1. Place down brown_glazed_terracotta and save world
2. Run amulet 
3. Run replace on that coordinate of brown_glazed _terracotta to border_block

### Environment:

- OS: Windows
- Minecraft Platform: Java/Bedrock
- Minecraft Version: 1.19.40
- Amulet Version: 0.10.2

### Additional context
Replace works with beta 0.10.2b0. Seems to stopped working with 0.10.2b3

**Comment by gentlegiantJGC** [comment]
I have tried reproducing the issue you described and it worked as intended.
1) Place blocks in game
![image](https://user-images.githubusercontent.com/11940194/198823560-4874d44d-3d30-4d96-8c48-58ca50d90d76.png)
2) Select and set options. Select `*` property in block to find to select all values for that property (ie all rotations)
![image](https://user-images.githubusercontent.com/11940194/198823602-bc40e697-d3d2-4eeb-8887-f359705f8313.png)
3) After replacing it visually looks like air because border blocks do not exist in Java and the Java resource pack is being used to render the world. I need to implement support for the Bedrock resource pack.
![image](https://user-images.githubusercontent.com/11940194/198823622-5dced0c6-e214-43fe-9a38-27252fa05930.png)
4) As seen in game.
![image](https://user-images.githubusercontent.com/11940194/198823660-dfee8f02-43b3-4e3c-baf6-a9bdfa1997cc.png)

**Comment by qmagnet** [comment]
I'll take another look. We seem to not able to swap that block for some reason
