### ISSUE TITLE
[Bug Report] World Folder Still Being Used After World Close.

### ISSUE THREAD

**Issue by PREMIEREHELL** [Amulet-Team/Amulet-Map-Editor#831]
### Current Behaviour:
You can not rename the World db folder after closing world unless you fully close the Amulet App,
### Expected behavior:
You should be able to rename the folder after closing the world.

### Steps To Reproduce:
1. Open A Bedrock world and close it.
2. Try to rename db Folder, it won't work
3. Close out Amulet App
4. Now you can rename,

### Environment:
Windows
Bedrock
Amulet Version: 0.10.5

**Comment by gentlegiantJGC** [comment]
I cannot reproduce this issue. I have tried in both the source and compiled version.

The steps I tried:
1) Open a world in Amulet (I tried both opening to the about page and the 3d editor)
2) Find the folder for the world opened in Amulet
3) Try and rename the db folder to confirm it is locked. Windows says no because it is open elsewhere.
4) Close the world in Amulet but not Amulet itself.
5) Rename the db folder. It renames with no issues.

Do you have any plugins that are storing the world or leveldb object and stopping it from being closed?

**Comment by PREMIEREHELL** [comment]
I will need to check and make sure. Im pretty sure they dont do anything until there used. But if you cant  Reproduce, I must be missing something on my end
