### ISSUE TITLE
[Bug Report] World not saving bedrock

### ISSUE THREAD

**Issue by dadodasyra** [Amulet-Team/Amulet-Map-Editor#835]
### Current Behaviour:

The world is not saving and an error is thrown on the console.
### Expected behavior:

The world should save as normal

### Steps To Reproduce:

1. Open a bedrock map
2. Edit anything (I tried removing blocks)
3. Save the map with Ctrl S
4. Nothing shown on the UI but the console is throwing an error

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version: 

### Additional context

This is probably related to the world. But I don't understand why

### Screenshots

Error: https://pastebin.com/RjDGritc

### Worlds

(The main thing is at x256 z256)
[areneboss.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/10049943/areneboss.zip)

**Comment by dadodasyra** [comment]
This is 100% related to the world level dat which comes from the PocketMine server software.
I tried the same db on a vanilla world and it doesnt occurs. 

Maybe you won't fix this bug but I think you should at least show on the UI that the save failed

**Comment by gentlegiantJGC** [comment]
The level.dat file does not include the maximum version tag.
It has revealed a couple of issues in Amulet that I have fixed.
Without a defined maximum version we assume the maximum version is 1.2 so any blocks newer than that will get removed.
I would suggest opening the level in the vanilla game so that it can write the extra tags or just copy over a level.dat file from another world.
