### ISSUE TITLE
je to be, the sea crystal lantern becomes an unknown block

### ISSUE THREAD

**Issue by loxehate** [Amulet-Team/Amulet-Map-Editor#949]
![Screenshot_20230731_145354](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/141010096/17926aba-d2cb-4b83-9711-4eef79630af7)

**Comment by superx101** [comment]
It's hard to help developers locate problems with this issues. I think you should change the title to English and give more complete information.

e.g.
> [Bug Report] Unknown block from java edition to bedrock edition. 
> Environment:
> - OS: 
> - Minecraft Java Edition Version: 
> - Minecraft Bedrock Edition Version: 
> - Amulet Version:

**Comment by gentlegiantJGC** [comment]
@loxehate please can you fill out the bug report template





## Bug Report

### Current Behaviour:


### Expected behavior:


### Steps To Reproduce:


### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version: 

### Additional context


## Attachments

### Screenshots


### Worlds

**Comment by gentlegiantJGC** [comment]
Please can check if this is still an issue in 0.10.25
